{% set name = "sbpy" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cc05852899711eafee1b1b238774c78d50fb13e585a03a8894fbfee74c01c3a1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - setuptools_scm
    - pip
  run:
    - python >=3.7
    - numpy >=1.17.0
    - astropy >=4.0
    - ads >=0.12
    - synphot >=1.0
    - astroquery >=0.4.5
    - scipy
    - photutils
    - pyyaml
    - ginga

test:
  imports:
    - sbpy
    - sbpy.units
    - sbpy.obsutil
    - sbpy.photometry

about:
  home: https://sbpy.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: sbpy is a Python package for small-body planetary astronomy.
  description: |
    sbpy is a community effort to build a Python package for small-body
    planetary astronomy in the form of an Astropy affiliated package. The
    goal is to collect and implement well-tested and well-documented code
    for the scientific study of asteroids and comets, including (but not
    limited to) observation planning, photometric models, spectroscopic
    analysis, asteroid thermal models, lightcurve and shape tools, and
    access tools for relevant databases.
  doc_url: https://sbpy.readthedocs.io/
  dev_url: https://github.com/NASA-Planetary-Science/sbpy

extra:
  recipe-maintainers:
    - mwcraig
